### ISSUE TITLE
Update/set Branching model?

### ISSUE THREAD

**Issue by hugodahl** [FritzAndFriends/StreamDeckEmulator#11]
Before we get in too deep into the development effort, do we want to setup a branching model such as the one in the [Stream Deck Toolkit][], i.e (work)->`dev`->`master`?

I started getting git-flow initialized on my computer when I noticed the lack of `dev` branch.

[Stream Deck Toolkit]: https://github.com/FritzAndFriends/StreamDeckToolkit

**Comment by codingbandit** [comment]
Yeah, I think now that multiple people are working on this and a pipeline is going to be put in place - this is a good idea

**Comment by csharpfritz** [comment]
Created dev branch and now protecting MASTER
