### ISSUE TITLE
The README.md has some inaccuracies

### ISSUE THREAD

**Issue by hugodahl** [FritzAndFriends/StreamDeckEmulator#15]
Since the `README.md` was written, several changes have taken place which affect the contents of the README.

* There are now more than one command available (was previously `keyUp`)
* The key chord to trigger the command which was available has changed (`b` => `kd`)
* The recommended method to quit the emulator is no longer <kbd>Ctrl</kbd>+<kbd>C</kbd>

There are currently some issues and limitations with the emulator which are worth documenting, such as:
* Only the first `Action` from the manifest currently works
* If the WebSocket connection is closed, or fails to open, no further communications will be made across the WebSocket
* If the application crashes, or is forcibly terminated, the `node` process may still be running, holdin the port, resulting in a "port is unavailable" type error restarting the emulator.

**Comment by codingbandit** [comment]
This has been remedied with @hugodahl 's PR :)  Thank you!!!
