### ISSUE TITLE
Make the Emulator able to run as a global npm cli tool

### ISSUE THREAD

**Issue by NotMyself** [FritzAndFriends/StreamDeckEmulator#8]
If we want to push this to npm for people to be able to use, they need a way to execute it.

- [x] Add bin executable CLI.
- [x] Ensure the CLI accepts a project path and executable name as parameters.
- [x] Investigate any other things needed to make `npm i -g streamdeckemulator` work.

**Comment by hugodahl** [comment]
From the discussion in the PR, but thought it's best to put in here:

If we want anyone building a plugin, regardless of template/platform, to be able to run the emulator to test a plugin, wouldn't it be easiest to take in as a sole parameter a path to the build, and from there, use the `manifest.json` to know how/what to launch, as well as, potentially, which action? Ultimately, that's what the SD uses, the `manifest.json`, no?
